import { FormStatus } from '../types/formStatus';
import db from '../config/db.js';

/**
 * Represents an application form submitted by a user. This type is used to define the structure of the data stored in the database and returned by the API.
 * - `id`: The unique identifier for the form (optional, as it is auto-generated by the database).
 * - `name`: The name of the applicant.
 * - `email`: The email address of the applicant.
 * - `created`: The date and time when the form was created.
 * - `status`: The current status of the application (e.g., pending, approved, rejected).
 */
export type ApplyForm = {
    id?: number;
    name: string;
    email: string;
    created: Date;
    status: FormStatus;
};

/**
 * Gets all the forms in the database. This is used for the admin dashboard to show all the applications.
 * @returns an array of ApplyForm objects.
 */
export const getAllForms = async (): Promise<ApplyForm[]> => {
    const [rows] = await db.query('SELECT * FROM applications');
    return rows as ApplyForm[];
};

/**
 * Deletes a form from the database by its id. This is used for the admin dashboard to delete applications that are no longer needed.
 * @param id - The id of the form to delete.
 * @return true if the form was deleted, false otherwise.
 */
export const deleteFormById = async (id: number): Promise<boolean> => {
    const [result] = await db.query('DELETE FROM applications WHERE id = ?', [id]);
    return (result as { affectedRows: number }).affectedRows > 0; // Return true if a row was deleted
};

/**
 * Updates the form status in the database by its id. This is used for the admin dashboard to update the status of applications.
 * @param id - The id of the form to update.
 * @param status - The new status to set for the form.
 * @returns true if the form was updated, false otherwise.
 */
export const updateFormStatus = async (id: number, status: FormStatus): Promise<boolean> => {
    const [result] = await db.query('UPDATE applications SET status = ? WHERE id = ?', [
        status,
        id,
    ]);
    return (result as { affectedRows: number }).affectedRows > 0; // Return true if a row was updated
};

/**
 * Creates a new form in the database. This is used for the user-facing API to submit new applications.
 * @param form - An object containing the name, email, and status of the form to create. The id and created fields are auto-generated by the database.
 * @returns the created ApplyForm object, including the generated id and created date.
 */
export const createForm = async (form: Omit<ApplyForm, 'id' | 'created'>): Promise<ApplyForm> => {
    const { name, email, status } = form;
    const [result] = await db.query(
        'INSERT INTO applications (name, email, created, status) VALUES (?, ?, ?, ?)',
        [name, email, new Date(), status],
    );
    const insertId = (result as { insertId: number }).insertId;
    return { id: insertId, name, email, created: new Date(), status };
};
